#!/usr/bin/env sh

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "shfmt"
ensure_command "shellcheck"

FILES=$(get_modified_files ":(exclude).githooksrc" ":(exclude).shellcheckrc")

[ -z "$FILES" ] && exit 0

# shellcheck disable=SC2086
FILES_TO_USE=$(shfmt -f $FILES)

[ -z "$FILES_TO_USE" ] && exit 0

echo "=> Check code format..."
(
  set -x
  # shellcheck disable=SC2086
  shfmt -d $FILES_TO_USE
)

echo "=> Check code lint...."
(
  set -x
  # shellcheck disable=SC2086
  shellcheck $FILES_TO_USE
)
