#!/usr/bin/env sh
#shellcheck disable=SC2086

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "shfmt"
ensure_command "shellcheck"

FILES=$(get_modified_files ":(exclude).githooksrc" ":(exclude).shellcheckrc")

# THIS MUST BE NEW LINE SEPERATED SO WE CAN EXPAND WHEN PASSIN TO CMD BELLOW
SHFMT_FLAGS="
-p
-d
-i
2
-ci
"
SHELLCHECK_FLAGS="
--extended-analysis=true
--shell=sh
"

[ -z "$FILES" ] && exit 0

OLD_IFS=$IFS
IFS="
"
FILES_TO_USE=$(shfmt -f $FILES)
IFS=$OLD_IFS

# FORMAT
if [ -n "$FILES_TO_USE" ]; then
  (
    IFS="
"
    run_and_print shfmt $SHFMT_FLAGS $FILES_TO_USE
  )
fi


# LINT
if [ -n "$FILES_TO_USE" ]; then
  (
    IFS="
"
    run_and_print shellcheck $SHELLCHECK_FLAGS $FILES_TO_USE
  )
fi
