#!/usr/bin/env sh

pids=""
test_files=$(find "$(dirname "$0")" -type f -name 'it-*.sh')

for file in $test_files; do
  docker run --rm --init -v "$PWD"/hooks:/app/hooks:ro -v "$PWD"/tests:/app/tests:ro git-hooks-test:latest timeout 5s sh "$file" &

  echo "[$!] Running $file"
  pids="$pids $!"
done

for pid in $pids; do
  wait "$pid"
  exit_code="$?"

  if [ $exit_code -eq 0 ]; then
    echo "$pid passed"
  else
    echo "$pid failed ($exit_code)"
    tests_failed=1
  fi
done

# shellcheck disable=SC2086
exit $tests_failed
