#!/usr/bin/env sh

set -e

BASEDIR=$(dirname "$0")

# shellcheck disable=SC1091
. "$BASEDIR"/_utils.sh

ensure_config

# shellcheck disable=SC1091
. ./.githooksrc

FILES=$(get_modified_files ":(exclude).githooksrc")

[ -z "$FILES" ] && exit 0
[ -z "$HOOKS" ] && exit 0

# shellcheck disable=SC2086
for hook in $HOOKS; do
  if [ ! -d "$BASEDIR"/"$hook" ]; then
    echo "Unknown $hook pre-commit"
    continue
  fi

  echo "Running $hook pre-commit"
  (
    set -x
    /usr/bin/env sh "$BASEDIR"/"$hook"/pre-commit
  )
  echo ""
done
