#!/usr/bin/env sh

set -e

BASEDIR=$(dirname "$0")

# shellcheck disable=SC1091
. "$BASEDIR"/_utils.sh

ensure_config

# shellcheck disable=SC1091
. ./.githooksrc

FILES=$(get_modified_files ":(exclude).githooksrc")

[ -z "$FILES" ] && exit 0

# shellcheck disable=SC2086
for i in $(split $HOOKS ","); do
  echo "Running $i pre-commit"
  (
    set -x
    /usr/bin/env sh "$BASEDIR"/"$i"/pre-commit
  )
  echo ""
done
