#!/usr/bin/env sh

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "deno"

FORMAT_FILES=$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx" "*.md" "*.json" "*.jsonc" "*.markdown")
LINT_FILES=$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx")

if [ -n "$FORMAT_FILES" ]; then
  echo "=> Check code format..."
  (
    set -x
    # shellcheck disable=SC2086
    deno fmt --check $FORMAT_FILES
  )
fi

if [ -n "$LINT_FILES" ]; then
  echo "=> Check code lint..."
  (
    set -x
    # shellcheck disable=SC2086
    deno lint $LINT_FILES
  )
fi
