#!/usr/bin/env sh
#shellcheck disable=SC2086

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "deno"

DENO_FORMAT_FILES="$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx" "*.md" "*.json" "*.jsonc" "*.markdown")"
DENO_LINT_FILES="$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx")"
HTML_FILES="$(get_modified_files "*.html")"
CSS_FILES="$(get_modified_files "*.css")"
MD_FILES="$(get_modified_files "*.md" "*.mdx")"

# FORMAT
if [ -n "$DENO_FORMAT_FILES" ]; then
  (
    IFS="
"
    run_and_print deno fmt --check $DENO_FORMAT_FILES
  )
fi

if [ -n "$HTML_FILES" ] || [ -n "$CSS_FILES" ]; then
  (
    IFS="
"
    run_and_print deno run -A --no-lock npm:prettier -c $HTML_FILES $CSS_FILES
  )
fi

# LINT
if [ -n "$DENO_LINT_FILES" ]; then
  (
    IFS="
"
    run_and_print deno lint $DENO_LINT_FILES
  )
fi

if [ -n "$HTML_FILES" ]; then
  (
    IFS="
"
    run_and_print deno run -A --no-lock npm:html-validate $HTML_FILES
  )
fi

if [ -n "$MD_FILES" ]; then
  (
    IFS="
"
    run_and_print deno run -A --no-lock npm:markdownlint-cli2 $MD_FILES
  )
fi
