#!/usr/bin/env sh
#shellcheck disable=SC2086

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "deno"

DENO_FORMAT_FILES="$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx" "*.md" "*.json" "*.jsonc" "*.markdown")"
DENO_LINT_FILES="$(get_modified_files "*.ts" "*.tsx" "*.js" "*.jsx")"
HTML_FILES="$(get_modified_files "*.html")"
CSS_FILES="$(get_modified_files "*.css")"

# FORMAT
run_if_not_empty "$DENO_FORMAT_FILES" run_and_print deno fmt --check $DENO_FORMAT_FILES
run_if_not_empty "$HTML_FILES" run_and_print deno run -A npm:prettier $HTML_FILES
run_if_not_empty "$CSS_FILES" run_and_print deno run -A npm:prettier $CSS_FILES

# LINT
run_if_not_empty "$DENO_LINT_FILES" run_and_print deno lint $DENO_LINT_FILES
run_if_not_empty "$HTML_FILES" run_and_print deno run -A npm:html-validate $HTML_FILES
