#!/usr/bin/env sh
#shellcheck disable=SC2086

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "sqlfluff"

FILES=$(get_modified_files "*.sql")

# FORMAT & LINT
if [ -n "$FILES" ]; then
  (
    IFS="
"
    run_and_print sqlfluff lint $FILES
  )
fi
