#!/usr/bin/env sh

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "sqlfluff"

FILES=$(get_modified_files "*.sql")

[ -z "$FILES" ] && exit 0

echo "=> Check code..."
(
  set -x
  # shellcheck disable=SC2086
  sqlfluff lint $FILES
)
