#!/usr/bin/env sh

set -e

# shellcheck disable=SC1091
. "$(dirname "$0")"/../_utils.sh

ensure_command "sqlfluff"
ensure_command "yamllint"

FILES=$(get_modified_files "*.yaml" "*.yml")

[ -z "$FILES" ] && exit 0

echo "=> Check code format..."
(
  set -x
  # shellcheck disable=SC2086
  yamlfmt -dry -lint $FILES
)

echo "=> Check code lint..."
(
  set -x
  # shellcheck disable=SC2086
  yamllint $FILES
)
