---
name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: setup tools
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: run code checks
        run: ./hooks/sh/pre-commit && ./hooks/yaml/pre-commit
